name: Deploy

on:
  push:
    branches:
      - main1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: hashilbasheer/argocd-test
        token: ${{ secrets.GHCR_TOKEN }}
    
    - name: Install yq
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq
        
        
    - name: Update deployment YAML
      run: |
        yq e '.spec.template.spec.containers[0].image = "ghcr.io/hashilbasheer/react-poc:e7d2610" ' deploy/deploy.yaml
    
      
      
    - name: Commit changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Committing the Images "
        git push

